"""
Django settings for AGHAMazingQuestMobile project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Optional: load local .env for development
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'unsafe-default-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Read allowed hosts from env (space separated), default to localhost for dev
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.dev',  # Adding a dot at the start covers all ngrok subdomains
    'unauthorised-boyce-telegrammatic.ngrok-free.dev'
]

# ADD THIS LINE: Required for Django 4.0+ to allow secure ngrok tunnels
CSRF_TRUSTED_ORIGINS = [
    'https://unauthorised-boyce-telegrammatic.ngrok-free.dev'
]

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework", 
    "rest_framework.authtoken",
    "rest_framework_simplejwt", 
    "drf_spectacular",
    "dj_rest_auth", 
    "allauth", 
    "allauth.account", 
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "accounts", 
    
    # "ar", 
   # "learning", 
    #"tours", 
   # "feedback", 
  #  "chatbot",
]

# Sites framework required by django-allauth
SITE_ID = int(os.environ.get('DJANGO_SITE_ID', 1))

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# django-allauth / social account provider settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            # Client id/secret should be set via environment variables or via admin
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

ACCOUNT_EMAIL_VERIFICATION = "optional"   # allow email, no forced confirm
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_ADAPTER = "accounts.adapters.NoEmailVerificationAdapter"




SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Use the custom user model from the accounts app
AUTH_USER_MODEL = 'accounts.User'

# Tell dj-rest-auth to use JWTs
REST_USE_JWT = True

# dj-rest-auth: disable the legacy token model (we use JWT)
TOKEN_MODEL = None

# Enable token blacklist app for simplejwt token rotation/blacklist support
INSTALLED_APPS += [
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'AGHAMazingQuestMobile API',
    'DESCRIPTION': 'API documentation for AGHAMazingQuestMobile project',
    'VERSION': '1.0.0',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'AGHAMazingQuestMobile.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AGHAMazingQuestMobile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',   # allow email login
    'django.contrib.auth.backends.ModelBackend',  # fallback
]

REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'accounts.serializers.CustomLoginSerializer',
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directory where `collectstatic` will collect static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'paoloandrei782@gmail.com'
EMAIL_HOST_PASSWORD = 'auvpgvtdoeinrbrp'  # your 16-char Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




# Media files (user uploads)
# `MEDIA_URL` is the URL prefix for media files and `MEDIA_ROOT` is
# the filesystem path where uploaded files are stored (used by collectstatic
# and served by nginx in production).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
